[package]
name = "vc_core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand="0.8"
sha2="0.10"
ed25519-dalek="2"
x25519-dalek="2"
hkdf="0.12"
serde={version="1",features=["derive"]}
bincode="1.3"
chacha20poly1305 = "0.10"
rand_core="0.6"
serde_bytes="0.11"
